### ISSUE TITLE
Cannot download ebook

### ISSUE THREAD

**Issue by kumiter** [hurlenko/orly#10]
Hello,

Could you please to take a look on below issue when I'm trying to download:

orly-0.1.6\src\epub\builder.rs:236:17:
assertion `left == right` failed
  left: 0
 right: 1
stack backtrace:
   0:     0x7ff7d2ae25c8 - <unknown>
   1:     0x7ff7d270adf9 - <unknown>
   2:     0x7ff7d2ad4c91 - <unknown>
   3:     0x7ff7d2ae3fa6 - <unknown>
   4:     0x7ff7d2ae389a - <unknown>
   5:     0x7ff7d2ae47a7 - <unknown>
   6:     0x7ff7d2ae41e7 - <unknown>
   7:     0x7ff7d2ae412f - <unknown>
   8:     0x7ff7d2ae4118 - <unknown>
   9:     0x7ff7d2c27a14 - locale_charset
  10:     0x7ff7d2c27bf3 - locale_charset
  11:     0x7ff7d2c292c4 - locale_charset
  12:     0x7ff7d2a02d6a - <unknown>
  13:     0x7ff7d26aec72 - <unknown>
  14:     0x7ff7d26c9377 - <unknown>
  15:     0x7ff7d26c0cef - <unknown>
  16:     0x7ff7d2653af0 - <unknown>
  17:     0x7ff7d26cb53b - <unknown>
  18:     0x7ff7d2bf6dec - locale_charset
  19:     0x7ffa3f20257d - BaseThreadInitThunk
  20:     0x7ffa40b4af28 - RtlUserThreadStart

![image](https://github.com/hurlenko/orly/assets/19830090/2a283157-90c7-4a87-90f3-eb62074d21a7)

**Comment by hurlenko** [comment]
What is the id of the book? I want to reproduce it

**Comment by kumiter** [comment]
> What is the id of the book? I want to reproduce it

Hi @hurlenko ,

Book's ID 9780071663489

Thank you.

**Comment by hurlenko** [comment]
@kumiter Try version 0.1.7

**Comment by kumiter** [comment]
Hi @hurlenko ,

Many thanks for your quick response, let me try and back to you the result.

**Comment by kumiter** [comment]
Hi @hurlenko ,

I can download ebook without issue. But there is some font issue with special characters. Example below:

- Original:
![image](https://github.com/hurlenko/orly/assets/19830090/b3328cca-3237-4619-bb07-4a7b081b7023)
![image](https://github.com/hurlenko/orly/assets/19830090/8ff56e4a-e877-4793-aef9-4c8f7740816f)

- Downloaded:
![image](https://github.com/hurlenko/orly/assets/19830090/67032425-82fe-4bca-8b1d-4fb6c34cad55)
![image](https://github.com/hurlenko/orly/assets/19830090/9564487c-6613-4b6c-909b-5f4841eaafe8)

**Comment by hurlenko** [comment]
I don't have this problem, it might be something with your reader

**Comment by kumiter** [comment]
Hi @hurlenko ,

I've tried both online and offline reader and also convert to PDF with same issue. Maybe relating with my font decoder during output process. 

Many thanks for your help.

**Comment by hurlenko** [comment]
There might be some errors because the source files of the book may contain incompatible css rules or html tags. This is something I don't really want to dig in. Many ebook readers deal with it just fine, but still, the epub files produced by orly are not always 100% correct. Even though i tried to fix all errors and make it pass the epubcheck validator, each book might contain some incompatible css or html. You can try to convert it to some other format like mobi using calibre before using. It helps sometimes
