### ISSUE TITLE
Stuck Login

### ISSUE THREAD

**Issue by HelloWorldDC** [hurlenko/orly#6]
Hi, I'm stuck at login for a long time, what should I do?

![image](https://github.com/hurlenko/orly/assets/79351507/f66a99ee-7b82-41eb-86d1-282dccce1d8c)
# #

**Comment by hurlenko** [comment]
Seems like something has changed in auth flow. Use cookie authorization for now

**Comment by hurlenko** [comment]
Should be fixed now
