### ISSUE TITLE
Error: AuthenticationFailed("Login request failed, make sure your email and password are correct . . .

### ISSUE THREAD

**Issue by bdklahn** [hurlenko/orly#7]
```bash
orly --creds  "<my-email>"  "${O_PASSWORD}" 9781838648817
[2024-02-25 21:53:46][INFO] Checking if password login is possible
[2024-02-25 21:53:47][INFO] Logging into Safari Books Online...
Error: AuthenticationFailed("Login request failed, make sure your email and password are correct: HTTP status client error (403 Forbidden) for url (https://api.oreilly.com/api/v1/auth/login/)")
```

I thought I'd try the `--cookie` setting, but I guess I don't understand what the "Browser Cookie" is.
(Also listed here https://www.oreilly.com/privacy-cookies.html)
My Chrome dev console network tab shows no request cookies with anything like that name, for the book page I am able to access.

I cleared my cookies for O'Reilly, logged back in, then was able to see a "BrowserCookie". But I still got an error.

**Comment by hurlenko** [comment]
The fix has been released in version 0.1.6
Tested both cookie and password-based authorization
